language: bash
services: docker

env:
  - VERSION=8-jre
  - VERSION=8-jdk

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - image="openjdk:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
